# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubebook_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writings',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
