# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubebook_main', '0002_auto_20160615_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameModel(
            old_name='WriteProfile',
            new_name='WriterProfile',
        ),
        migrations.DeleteModel(
            name='Writings',
        ),
    ]
