# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubebook_main', '0003_auto_20160615_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerprofile',
            name='picture_url',
            field=models.CharField(max_length=500),
        ),
    ]
